### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by tukyab** [femaidens/2015-Robot-Code#1]
need to make sense...
moveforward() in tote()? why tote()? need to make logical sense.

**Comment by karennguyen** [comment]
idk anna wanted us to have a method to pick up the tote and move forward all in one. also tote was a random name for the method of lifting the tote up so you could change it to anything

**Comment by galloa** [comment]
Names of methods should NEVER be random. They always have to be descriptive and make sense.
